name: syntaxity_wallpaper
description: "This is a wallpaper Android based app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  photo_view: ^0.14.0
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.1
  path_provider: ^2.1.2
  sqflite: ^2.3.1
  path: ^1.8.3
  flutter_wallpaper_manager: ^0.0.4
  async_wallpaper: ^2.0.3
  # fluttertoast: ^8.2.4
  # bitmap: ^0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
